### ISSUE TITLE
MAXSatPipeline Error for "Discarding the resulting clauses not having optimal support"

### ISSUE THREAD

**Issue by SamuelAppleby** [datagram-db/knobab#37]
With the following data, there is an error during the "// Discarding the resulting clauses not having optimal support" part of the pipeline, specifically when re-running the maxsat pipeline: ref.pipeline(&tmpEnv.grounding, tmpEnv.ap, tmpEnv.db). 

The error is the following assertion (MAXSatPipeline.cpp, Line 1338):

DEBUG_ASSERT((formula->table_query.size() == 1) != (!formula->range_query.empty()));

[world_0.txt](https://github.com/datagram-db/knobab/files/11726009/world_0.txt)
[world_1.txt](https://github.com/datagram-db/knobab/files/11726012/world_1.txt)

**Comment by jackbergus** [comment]
This is very likely to be referred to the following novel introduction in KnoBAB so to support the data mining pipeline:

- Previously, the Absence1, Absence2 and Exists1, Exists2... patterns were explicitly defined in the semantics ".sem" file (now expressed through the query plan query). Still, this needed to be more scalable to handle any potential Absence and Exists being generated by the Data Mining pipeline. Please compare the ```std::string query_plan``` in refinery.cpp and the previous semantics file. Now, Absence and Exists are defined with a dollar sign, referring to the fact that the number of the exists needs to be inferred from the number argument ```.n``` coming from the DeclareDataAware representation. 
- In my previous tests, these never occurred to be refined nor to have been preserved until the testing phase, and therefore never tested in the MAXSatPipeline.

**Comment by jackbergus** [comment]
Please let me know if this work, there was a missing line from the previous version of KnoBAB: https://github.com/datagram-db/knobab/blob/51b927205d739067c587cc6b10a52760383be03d/src/knobab/algorithms/atomization_pipeline.cpp#L229
This solved the issue locally.

**Comment by SamuelAppleby** [comment]
> Please let me know if this work, there was a missing line from the previous version of KnoBAB:
> 
> https://github.com/datagram-db/knobab/blob/51b927205d739067c587cc6b10a52760383be03d/src/knobab/algorithms/atomization_pipeline.cpp#L229
> 
> 
> This solved the issue locally.

Yes this has solved the bug, closing the case.
