### ISSUE TITLE
Refining Interval Overlap

### ISSUE THREAD

**Issue by SamuelAppleby** [datagram-db/knobab#38]
When running the mining pipeline on the following worlds, if the code related to issue https://github.com/datagram-db/knobab/issues/37 is commented the result is as follows:

The intervals assigned to ChainSuccession and Exists have overlaps across the worlds, for example:

A, x = 1.5, y = 1.5, will satisfy both the worlds' activation conditions for ChainSuccession and Exists.

[world_0.txt](https://github.com/datagram-db/knobab/files/11726074/world_0.txt)
[world_1.txt](https://github.com/datagram-db/knobab/files/11726077/world_1.txt)

~~~ model ~~~
Absence(A, true, 3 )
Absence(B, true, 3 )
Absence(C, true, 2 )
CoExistence(C, true, A, true )
CoExistence(C, true, B, true )
ChainSuccession(A, (A.y >= 7.5 ∧ A.x >= 1.5) ∨ (1.5 ≤ A.y ≤ 7.5 ∧ A.x >= 1.5), B, true )
Exists(A, (A.y >= 7.5 ∧ A.x >= 1.5) ∨ (1.5 ≤ A.y ≤ 7.5 ∧ A.x >= 1.5), 1 )
~~~ model ~~~
Absence(A, true, 3 )
Absence(B, true, 3 )
Absence(C, true, 2 )
CoExistence(C, true, A, true )
CoExistence(C, true, B, true )
ChainSuccession(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ 1.5 ≤ A.x ≤ 1.5), B, true )
Exists(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ 1.5 ≤ A.x ≤ 1.5), 1 )

**Comment by jackbergus** [comment]
It might be the case that the algorithm needs to be more coarse-grained in picking the numeric values to divide the two classes, thus resulting in some overlaps, although there should be none. This might be optimized in a later post-processing step by taking the immediately preceding and following number of 1.5 via [nextafter](https://en.cppreference.com/w/cpp/numeric/math/nextafter), or by upgrading the decision tree algorithm by directly picking stricter numbers (although this other implementation tries to avoid overfitting).

**Comment by SamuelAppleby** [comment]
This issue is resolved as of https://github.com/datagram-db/knobab/commit/d952cf0699327b9a618e8b288c007fe41512e317
