### ISSUE TITLE
Refining Equality Not Defined

### ISSUE THREAD

**Issue by SamuelAppleby** [datagram-db/knobab#39]
When running the mining pipeline on the following worlds, if the code related to issue https://github.com/datagram-db/knobab/issues/37 is commented the result is as follows:

For the refined clauses, intervals seem to be assigned where equality should be:

E.g. ChainSuccession(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ 1.5 ≤ A.x ≤ 1.5), B, true ) should be 
ChainSuccession(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ A.x = 1.5), B, true )

[world_0.txt](https://github.com/datagram-db/knobab/files/11726105/world_0.txt)
[world_1.txt](https://github.com/datagram-db/knobab/files/11726106/world_1.txt)

~~~ model ~~~
Absence(A, true, 3 )
Absence(B, true, 3 )
Absence(C, true, 2 )
CoExistence(C, true, A, true )
CoExistence(C, true, B, true )
ChainSuccession(A, (A.y >= 7.5 ∧ A.x >= 1.5) ∨ (1.5 ≤ A.y ≤ 7.5 ∧ A.x >= 1.5), B, true )
Exists(A, (A.y >= 7.5 ∧ A.x >= 1.5) ∨ (1.5 ≤ A.y ≤ 7.5 ∧ A.x >= 1.5), 1 )
~~~ model ~~~
Absence(A, true, 3 )
Absence(B, true, 3 )
Absence(C, true, 2 )
CoExistence(C, true, A, true )
CoExistence(C, true, B, true )
ChainSuccession(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ 1.5 ≤ A.x ≤ 1.5), B, true )
Exists(A, (A.y <= 1.5 ∧ A.x >= 1.5) ∨ (A.y <= 7.5 ∧ 1.5 ≤ A.x ≤ 1.5), 1 )

**Comment by jackbergus** [comment]
If referring to (A.y <= 1.5 ∧ A.x >= 1.5, please observe that y and x are
different variables.
Otherwise, this is not incorrect for 1.5 ≤ A.x ≤ 1.5, which can be refined
later in the formula simplification step.
All the preliminary implementations of the formula simplification
algorithms start from interval decomposition. So, transforming the
less-equal in a point to equality is just post-processing.

I changed this to "optimization" rather than to bug.

**Comment by SamuelAppleby** [comment]
> If referring to (A.y <= 1.5 ∧ A.x >= 1.5, please observe that y and x are different variables. Otherwise, this is not incorrect for 1.5 ≤ A.x ≤ 1.5, which can be refined later in the formula simplification step. All the preliminary implementations of the formula simplification algorithms start from interval decomposition. So, transforming the less-equal in a point to equality is just post-processing. I changed this to "optimization" rather than to bug.

That makes sense, I'll leave this open for the time being.

**Comment by jackbergus** [comment]
Sure, keeping this an optimisation task so as to provide better results by minimising the overall boolean formula.

**Comment by SamuelAppleby** [comment]
Adding a note here based on today's discussion:

An interval is ALWAYS found with numerical data. Therefore, the value that the predicate uses is NEVER found in the data itself. Under these assumptions, then if the range is between the same value, it equates to false.

**Comment by SamuelAppleby** [comment]
This issue seems to be resolved as of [commit](https://github.com/datagram-db/knobab/commit/d952cf0699327b9a618e8b288c007fe41512e317)
