### ISSUE TITLE
Decision Tree Bug

### ISSUE THREAD

**Issue by SamuelAppleby** [datagram-db/knobab#44]
With the attached data, the decision tree reaches the following location and returns a zero-depth tree even when there should have been a suitable separation.
[choice_0.txt](https://github.com/datagram-db/knobab/files/11748509/choice_0.txt)
[choice_1.txt](https://github.com/datagram-db/knobab/files/11748510/choice_1.txt)

        if ((begin == it2) || (it2 == end)) {
            isLeaf = true;
            majority_class = clazz;
            majority_class_precision = forthegain.getClassPrecision(clazz);
            leaf = {begin, end};
            *total_weights += current_weight;
            *goodness += (majority_class_precision * current_weight);
            return;
        }

**Comment by jackbergus** [comment]
When this happens, it means that the best separation only separates the
whole data in one branch where the rest is empty (either the begin is
matching the separation between classes or it2 is the ), thus entailing
that no better separation than this can be inferred.

Il Mer 14 Giu 2023, 17:33 SamuelAppleby ***@***.***> ha
scritto:

**Comment by jackbergus** [comment]
After the e-mail discussion, please consider adding the code below before this https://github.com/datagramdb/yaucl/blob/eb5d45e365baf114f48916dd72369aa2bb9d59c4/include/yaucl/learning/DecisionTree.h#L113 line:

```
    if ((forthepos ==  0) || (fortheneg == 0)) {
       predicate_w_score.second = -1;
       return predicate_w_score;
    }
```

**Comment by SamuelAppleby** [comment]
Fixed as of https://github.com/datagramdb/yaucl/commit/8249226d6eea277a169dc8f5cfc94d373603764a
