### ISSUE TITLE
FPGrowth rendition, visiting bug

### ISSUE THREAD

**Issue by jackbergus** [datagram-db/knobab#47]
There is an issue with the FPGrowth view heuristic, where you were re-visiting the node up until you get all of your siblings. Due to force majeure, you are still forced to visit all the nodes from the descendants to the root. Incoming fix (to be double checked)

**Comment by jackbergus** [comment]
Samuel, please double check whether this commit fixes it with some more tests: https://github.com/datagram-db/knobab/commit/44258507005d3b810799548593cf3588bafd4c71

**Comment by SamuelAppleby** [comment]
Upon further testing, the changes from https://github.com/datagram-db/knobab/commit/44258507005d3b810799548593cf3588bafd4c71 have solved the issue. The appropriate frequent patterns are now returned from FPGrowth.
